spring:
  application:
    name: spring-redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数的时候才有效）
      min-idle: 0
      # 从连接池获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1
